version: '3.6'
services:
  app-prod:
      image: "frontjokerz"
      container_name: dockerized-react-app
      build:
        context: .
        dockerfile: Dockerfile-prod
      ports:
        - 5000:80
  reverse-proxy:
    image: valian/docker-nginx-auto-ssl:1.0.0
    container_name: reverse-proxy
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.ssl-data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'teamjokerz.com.br'
      SITES: 'teamjokerz.com.br=app-prod:80'
      FORCE_HTTPS: "true"
    depends_on:
      - app-prod
volumes:
  .ssl-data: