version: '3'
services:
    app-prod:
        image: "frontjokerz"
        container_name: dockerized-react-app
        build:
          context: .
          dockerfile: Dockerfile-prod
        ports:
          - '80:80'