export const LOAD_PREMIACOES = 'LOAD_PREMIACOES';
export const CADASTRAR_PREMIACAO = 'CADASTRAR_PREMIACAO';
export const DELETE_PREMIACAO = 'DELETE_PREMIACAO';
export const SET_PREMIACOES = 'SET_PREMIACOES';
export const SET_LOADING_PREMIACAO = 'SET_LOADING_PREMIACAO';
export const SET_ERROR_PREMIACAO = 'SET_ERROR_PREMIACAO';
export const SET_RESPONSE_PREMIACAO = 'SET_RESPONSE_PREMIACAO';
export const SET_STATUS_PREMIACAO = 'SET_STATUS_PREMIACAO';
