export const LOAD_CATEGORIAS = 'LOAD_CATEGORIAS';
export const CADASTRAR_CATEGORIA = 'CADASTRAR_CATEGORIA';
export const DELETE_CATEGORIA = 'DELETE_CATEGORIA';
export const SET_CATEGORIAS = 'SET_CATEGORIAS';
export const SET_LOADING_CATEGORIA = 'SET_LOADING_CATEGORIA';
export const SET_ERROR_CATEGORIA = 'SET_ERROR_CATEGORIA';
export const SET_RESPONSE_CATEGORIA = 'SET_RESPONSE_CATEGORIA';
export const SET_STATUS_CATEGORIA = 'SET_STATUS_CATEGORIA';
