export const LOAD_REDEEM_POINTS = 'LOAD_REDEEM_POINTS';
export const SET_REDEEM_POINTS = 'SET_REDEEM_POINTS';
export const SET_LOADING_REDEEM_POINTS = 'SET_LOADING_REDEEM_POINTS';
export const SET_ERROR_REDEEM_POINTS = 'SET_ERROR_REDEEM_POINTS';
export const SET_RESPONSE_REDEEM_POINTS = 'SET_RESPONSE_REDEEM_POINTS';
export const SET_STATUS_REDEEM_POINTS = 'SET_STATUS_REDEEM_POINTS';
export const RESTORE_POINTS_STREAM_ELEMENTS = 'RESTORE_POINTS_STREAM_ELEMENTS';
