export const LOAD_PARTIDAS = 'LOAD_PARTIDAS';
export const LOAD_PARTIDA_ATUAL = 'LOAD_PARTIDA_ATUAL';
export const CADASTRAR_PARTIDA = 'CADASTRAR_PARTIDA';
export const DELETE_PARTIDA = 'DELETE_PARTIDA';
export const SET_PARTIDAS = 'SET_PARTIDAS';
export const SET_PARTIDA = 'SET_PARTIDA';
export const SET_LOADING_PARTIDA = 'SET_LOADING_PARTIDA';
export const SET_ERROR_PARTIDA = 'SET_ERROR_PARTIDA';
export const SET_RESPONSE_PARTIDA = 'SET_RESPONSE_PARTIDA';
export const SET_STATUS_PARTIDA = 'SET_STATUS_PARTIDA';

//Partida
//PARTIDA
//PARTIDAS
//partidas
//partida