
export const LOAD_CHANNELS = 'LOAD_CHANNELS';
export const SET_LOADING_CHANNELS = 'SET_LOADING_CHANNELS';
export const SET_ERROR_CHANNELS = 'SET_ERROR_CHANNELS';
export const SET_RESPONSE_CHANNELS = 'SET_RESPONSE_CHANNELS';
export const SET_STATUS_CHANNELS = 'SET_STATUS_CHANNELS';
export const SET_CHANNELS = 'SET_CHANNELS';
