export const LOAD_PERGUNTAS = 'LOAD_PERGUNTAS';
export const CADASTRAR_PERGUNTA = 'CADASTRAR_PERGUNTA';
export const DELETE_PERGUNTA = 'DELETE_PERGUNTA';
export const SET_PERGUNTAS = 'SET_PERGUNTAS';
export const SET_LOADING_PERGUNTA = 'SET_LOADING_PERGUNTA';
export const SET_ERROR_PERGUNTA = 'SET_ERROR_PERGUNTA';
export const SET_RESPONSE_PERGUNTA = 'SET_RESPONSE_PERGUNTA';
export const SET_STATUS_PERGUNTA = 'SET_STATUS_PERGUNTA';
