export const LOAD_REWARDS = 'LOAD_REWARDS';
export const SET_REWARDS = 'SET_REWARDS';
export const CREATE_REWARD = 'CREATE_REWARD';
export const SET_LOADING_REWARDS = 'SET_LOADING_REWARDS';
export const SET_ERROR_REWARDS = 'SET_ERROR_REWARDS';
export const SET_RESPONSE_REWARDS = 'SET_RESPONSE_REWARDS';
export const SET_STATUS_REWARDS = 'SET_STATUS_REWARDS';
export const DELETE_REWARD = 'DELETE_REWARD';
