export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_LOADING_PRODUCTS = 'SET_LOADING_PRODUCTS';
export const SET_ERROR_PRODUCTS = 'SET_ERROR_PRODUCTS';
export const SET_RESPONSE_PRODUCTS = 'SET_RESPONSE_PRODUCTS';
export const SET_STATUS_PRODUCTS = 'SET_STATUS_PRODUCTS';