export const LOAD_NIVEIS = 'LOAD_NIVEIS';
export const CADASTRAR_NIVEL = 'CADASTRAR_NIVEL';
export const DELETE_NIVEL = 'DELETE_NIVEL';
export const SET_NIVEIS = 'SET_NIVEIS';
export const SET_LOADING_NIVEL = 'SET_LOADING_NIVEL';
export const SET_ERROR_NIVEL = 'SET_ERROR_NIVEL';
export const SET_RESPONSE_NIVEL = 'SET_RESPONSE_NIVEL';
export const SET_STATUS_NIVEL = 'SET_STATUS_NIVEL';
