export const GET_URL_AUTH_TWITCH = 'GET_URL_AUTH_TWITCH';
export const SET_URL_AUTH_TWITCH = 'SET_URL_AUTH_TWITCH';
export const AUTH_CODE_TWITCH = 'AUTH_CODE_TWITCH';
export const SET_RESPONSE_LOGIN = 'SET_RESPONSE_LOGIN';
export const SET_LOADING_LOGIN = 'SET_LOADING_LOGIN';
export const SET_STATUS_LOGIN = 'SET_STATUS_LOGIN';
export const SET_ERROR_LOGIN = 'SET_ERROR_LOGIN';
